[2024-08-25T08:27:41.883+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-25T08:27:41.949+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill_v1.task1 scheduled__2024-08-21T00:00:00+00:00 [queued]>
[2024-08-25T08:27:41.980+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_and_backfill_v1.task1 scheduled__2024-08-21T00:00:00+00:00 [queued]>
[2024-08-25T08:27:41.981+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 6
[2024-08-25T08:27:42.035+0000] {taskinstance.py:2879} INFO - Executing <Task(BashOperator): task1> on 2024-08-21 00:00:00+00:00
[2024-08-25T08:27:42.057+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1588) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-25T08:27:42.064+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_and_backfill_v1', 'task1', 'scheduled__2024-08-21T00:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_and_backfill.py', '--cfg-path', '/tmp/tmp5iz31p6t']
[2024-08-25T08:27:42.076+0000] {standard_task_runner.py:72} INFO - Started process 1592 to run task
[2024-08-25T08:27:42.079+0000] {standard_task_runner.py:105} INFO - Job 65: Subtask task1
[2024-08-25T08:27:42.286+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_and_backfill_v1.task1 scheduled__2024-08-21T00:00:00+00:00 [running]> on host ae952724060e
[2024-08-25T08:27:42.767+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shreyas' AIRFLOW_CTX_DAG_ID='dag_with_catchup_and_backfill_v1' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-21T00:00:00+00:00'
[2024-08-25T08:27:42.770+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-25T08:27:42.864+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-25T08:27:42.888+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo This is a simple bash command!']
[2024-08-25T08:27:42.991+0000] {subprocess.py:86} INFO - Output:
[2024-08-25T08:27:42.996+0000] {subprocess.py:93} INFO - This is a simple bash command!
[2024-08-25T08:27:43.010+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-25T08:27:43.307+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-25T08:27:43.318+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_and_backfill_v1, task_id=task1, run_id=scheduled__2024-08-21T00:00:00+00:00, execution_date=20240821T000000, start_date=20240825T082741, end_date=20240825T082743
[2024-08-25T08:27:43.417+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-25T08:27:43.478+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-25T08:27:43.484+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
